spring.application.name=api-gateway
server.port=8090
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# 1. Define the unique ID for the route
spring.cloud.gateway.server.webmvc.routes[0].id=order-service

# 2. Use the LoadBalancer (lb://) to find the service in Eureka
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://order-service

# 3. Match any request that starts with /order-service/
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/order-service/**

# 4. Strip the "/order-service" prefix before forwarding
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1